name: Build Packages

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to build"
        required: true
      full_bootstrap:
        description: "Full bootstrap"
        required: false
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Update Package Cache
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel
          sed -i '/E_ROOT/d' /usr/bin/makepkg

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install and Start tmate
        run: |
          pacman -S --noconfirm tmate
          tmate -F

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: /bin/true
          tag: artifact
          overwrite: true
          file_glob: true
